name: Auto Create PR from Main to Staging

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto-sync: Update from main'
          branch: main
          base: staging  # This is where the target branch is set to 'staging'
          title: 'Auto PR: Sync changes from main to staging'
          body: 'This PR automatically syncs changes from the main branch to staging.'
