name: Auto PR from Main to Staging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write  

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git for commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch staging branch 
        run: git fetch origin staging

      - name: Check for differences
        id: check_diff
        run: |
          git diff --quiet origin/staging HEAD
        continue-on-error: true  

      - name: Create new Pull Request
        if: ${{ steps.check_diff.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base staging --head main \
          --title "Auto PR: Sync changes from main to staging" \
          --body "This PR automatically syncs changes from the main branch to staging."
