name: Auto PR from Main to Staging

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write  

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch staging branch 
        run: git fetch origin staging

      - name: Check for differences
        id: check_diff
        run: |
          git diff --quiet origin/staging HEAD
        continue-on-error: true 

      - name: Check if Pull Request exists
        if: ${{ steps.check_diff.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          pr_number=$(gh pr list --base staging --head main --json number --jq '.[].number')
          if [ -n "$pr_number" ]; then
            echo "PR #$pr_number exists"
            echo "pr_number=$pr_number" >> $GITHUB_ENV
          else
            echo "pr_number=none" >> $GITHUB_ENV
          fi

      - name: Create new Pull Request if none exists
        if: ${{ env.pr_number == 'none' && steps.check_diff.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base staging --head main \
          --title "Auto PR: Sync changes from main to staging" \
          --body "This PR automatically syncs changes from the main branch to staging."
          
      - name: Add comment to existing PR
        if: ${{ env.pr_number != 'none' && steps.check_diff.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ env.pr_number }} --body "new changes found and automatically added here."
